name: Deploying

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          port: 4565
          host: 3.141.15.114
          username: ${{ secrets.AWS_USER }}
          key: MIIEowIBAAKCAQEAhh5lmfRy9ziF+QRamQfdrwPy/clwjLc+XBqLsq3fesO3ve6bcvCEiuvYjfeq930hqPSVLoZtD3RnThUUiTq7RcT7GL9LtEUZBde1NkoW3KGn+CFJxOfKeaHY1sLKYbcWX629W0yXY4XpwaY3D3fSLY8ptcZkjcSEAgtUgeq9W51UiujK8ydSxjuZ0c2m/4KFrBdfmeVKJTEjlAarsK+COqUSvydWl/2lGbxiZXaNIS+1vLzPq2aj9TaFRyAuwzVdUAjU2eeEBuOI/dGqBUE+W3Lge9fBrR+V+Jz2Dn95p2RxGB1tW4wNiv9l1SKwP2xAxWZzJdVhNekNoZFV6x5zhwIDAQABAoIBAGLf5/FfCJ5/ei1B63SkGuda1voIVsQ2l2+ZVmHs0zOTNFN+o/VRobU0+Bp5ev4nrvf7EDwTeDWLkFk9Kz2cIdHmzWLKLIqC4lavVvXmGwKe3tEL4XGbnGadTdnOExuEuabh1BaJ2ZXSdKmB21e48ycJQyuyThFBzjwflDaPEviFY5tynTCXiANUiXEdQRpCL0/JglOPkzWXQ6fzd7Rq1gIctK+eY/17dYWVexCPMncUciSHmV0sz82lIW9T/uHU/ikhrwhzUZsYtzzmDeBAqTwir0TK1CcHlxdqBorajWkLOBrVIzquAtDzmsVD+SrDzZaMaEIRRiF2LT4Wwuy3LGECgYEA7jvf7u7avvFa0Hkm/jW8/S96ZO2aqPdNBcE0sbXji9jRw7FNN+YkxkMdCM4d+gXruE6pSExFiUizj+6LTvUUtUG1nIUOQuIhlvWd9e4jRSMAOdJq1LMPwcwI7SoS/EQV7eGfmeRP5gIlDSPJRPTiEShu7mqLp/6jxr/CCV+8yLcCgYEAkB7b4cJkTRzFdolzztGLB1myVkudT0CEsCcakY/AmEI+ActHzrgJ7gjPd9MXWAq+wabYsFddsYAUAunH8ipluoKbrqs2nWUHBrxNx2WJypbEmgsdU2CnaM8yH3Lq4VpLuYc0BaTkM3OEyA2mzr8ecBhDsQ6NU6jm5SoilkbWu7ECgYAnUTpj9Iele6/BOD13Nuc54dwRTCV6PVY43OoVai9jpST5ZwmXcCQhlHH2Qg4wdUmx4UmO5QeU4KrB1lyna0s/ntiaPFteLnPctiybqfGoN16SLGf1MpgnI8VVXtxDRflYiSQOAeAt1azHvmA5QTEOI94q+uqRjzT4WC1t3p8JgQKBgHxuGDvPwReO2rHgNNuAsT90YvP8ruII+0a3TEoWyhrrPmwAHYxN+0zH0JBM8Z+zD0VVD0sY8yzYPu7Q9y+PCWvBbjadXjcATdOz6pdYhGIkT7QMGpKtJXzpPwZGCqLseerB39lrpxcBCshKeRWRju8LFA6fWMe9UTTUby4+FRHRAoGBAKSuQmPcBz4NtiKV45T5qz+1qHL1sV0QgbvM0leGo7z539PK1NNgLR6Urvfdnt4aW4Aa2AeaAf0A9EA3PPXYvTe+JCZ1ynFluO6ZEpAqc9VVquhhOlTdBZLXyEOTx/n+Ukg8lpVpy3uqDs07c/zzdxTUP8SYndLIPYygLHkdoLW+
          script: sh /var/www/html/Bodega502-Proyecto-Ing-Software/AppWeb_Proyecto/bodega502/deploy.sh
